AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An app (read/write to DynamoDB) with a RESTful API endpoint using Amazon
  API Gateway.
Parameters:
  Stage:
    Type: String
Globals:
  Api:
    OpenApiVersion: 3.0.3
  Function:
    Runtime: python3.8
    MemorySize: 512
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME:
          Ref: DynamoDBTable
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: RestApi
      Description: An API for serverless app
      StageName:
        Ref: Stage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://announcement-app/artifacts/dev/e1644cffff5dd1db896313958269c21e
  AddAnnouncement:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AddAnnouncement
      Handler: lambda_add_item.add_announcement
      Description: Write to DynamoDB through a RESTful API endpoint using Amazon API
        Gateway.
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /announcements/add
            Method: post
            RestApiId:
              Ref: RestApi
      CodeUri: s3://announcement-app/artifacts/dev/ef4456e6bac87d27f23dedc18ded7d61
  GetAllAnnouncements:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAllAnnouncements
      Handler: lambda_get_all_items.list_announcements
      Description: Read from DynamoDB through a RESTful API endpoint using Amazon
        API Gateway.
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /announcements
            Method: get
            RestApiId:
              Ref: RestApi
      CodeUri: s3://announcement-app/artifacts/dev/ef4456e6bac87d27f23dedc18ded7d61
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: title
        AttributeType: S
      - AttributeName: date-time
        AttributeType: S
      KeySchema:
      - AttributeName: title
        KeyType: HASH
      - AttributeName: date-time
        KeyType: RANGE
      TableName: announcements
      BillingMode: PAY_PER_REQUEST
