AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An app (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Parameters:
  Stage:
    Type: String

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Api:
    OpenApiVersion: 3.0.3
  Function:
    Runtime: python3.8
    MemorySize: 512
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME:
          Ref: DynamoDBTable

Resources:
  RestApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: RestApi
      Description: An API for serverless app
      StageName:
        Ref: Stage
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: ./openapi.yaml
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
  AddAnnouncement:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: AddAnnouncement
      Handler: lambda_add_item.add_announcement
      Description: Write to DynamoDB through a RESTful API endpoint using Amazon API Gateway.
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /announcements/add
            Method: post
            RestApiId:
              Ref: RestApi
      CodeUri: ./my-deployment-package.zip

  GetAllAnnouncements:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetAllAnnouncements
      Handler: lambda_get_all_items.list_announcements
      Description: Read from DynamoDB through a RESTful API endpoint using Amazon API Gateway.
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /announcements
            Method: get
            RestApiId:
              Ref: RestApi
      CodeUri: ./my-deployment-package.zip

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
        - AttributeName: date-time
          AttributeType: S
      KeySchema:
        - AttributeName: title
          KeyType: HASH
        - AttributeName: date-time
          KeyType: RANGE
      TableName: announcements
      BillingMode: PAY_PER_REQUEST

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CognitoUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Ref CognitoUserPoolClientName
      GenerateSecret: false
